services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        working_dir: /var/www/html
